import Link from "next/link";

export default function Privacy() {
 
    return (
      <div className="w-[70vw] h-full flex flex-col gap-4 justify-start items-center">
         
              <div className="w-full max-w-4xl p-6 mb-4 bg-white rounded-md shadow-lg">
                  <div className="flex flex-col gap-2 items-center justify-center mx-auto">
                      <Link href="/"><h1 className="font-bold text-5xl">School</h1></Link>
                      <p className="text-xl">Privacy Policy</p>
                  </div>
  
                  
                  <p className="mt-8 text-md font-light text-center text-gray-400"> 
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Faucibus purus in massa tempor nec feugiat nisl pretium. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Eget mi proin sed libero enim. Facilisi nullam vehicula ipsum a arcu. Nisl purus in mollis nunc sed id. Dui ut ornare lectus sit amet est placerat in egestas. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Est placerat in egestas erat imperdiet sed euismod. Aliquam etiam erat velit scelerisque. Senectus et netus et malesuada fames ac.
                      <br />
                      Diam quam nulla porttitor massa id neque aliquam. Sodales ut etiam sit amet nisl purus in. Ante in nibh mauris cursus. Orci porta non pulvinar neque laoreet. Quam elementum pulvinar etiam non. Dignissim sodales ut eu sem. In ante metus dictum at tempor commodo ullamcorper a. Blandit volutpat maecenas volutpat blandit aliquam etiam. Phasellus vestibulum lorem sed risus. Varius vel pharetra vel turpis nunc eget lorem dolor. Integer enim neque volutpat ac tincidunt vitae. Morbi tristique senectus et netus et. Aliquet bibendum enim facilisis gravida neque convallis a. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Eget est lorem ipsum dolor sit amet. Commodo nulla facilisi nullam vehicula ipsum a.
                      <br />
                      Diam quam nulla porttitor massa id neque aliquam. Sit amet est placerat in egestas erat imperdiet sed. Morbi tempus iaculis urna id. Quis blandit turpis cursus in hac habitasse platea. Sit amet mauris commodo quis imperdiet massa. Ut tristique et egestas quis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Magna ac placerat vestibulum lectus mauris ultrices.
                      <br />
                      Laoreet sit amet cursus sit amet dictum sit. Id velit ut tortor pretium viverra suspendisse potenti. Est ante in nibh mauris cursus mattis molestie a. Semper quis lectus nulla at volutpat diam. Senectus et netus et malesuada fames ac turpis egestas. Eu consequat ac felis donec et odio pellentesque diam volutpat. Volutpat est velit egestas dui id ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada. Pharetra vel turpis nunc eget lorem dolor sed. Donec ac odio tempor orci dapibus ultrices in iaculis. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Duis ultricies lacus sed turpis. Facilisis volutpat est velit egestas.
                      <br />
                      Aliquet nec ullamcorper sit amet risus nullam eget felis. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Dolor sit amet consectetur adipiscing elit. Nisl rhoncus mattis rhoncus urna. Varius sit amet mattis vulputate enim nulla aliquet. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Ultrices eros in cursus turpis massa tincidunt. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Dis parturient montes nascetur ridiculus mus. Tortor at risus viverra adipiscing at in. Arcu dictum varius duis at consectetur lorem.
                      <br />
                      At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Vitae proin sagittis nisl rhoncus mattis rhoncus. Purus in massa tempor nec. Feugiat in fermentum posuere urna nec tincidunt praesent. In metus vulputate eu scelerisque felis imperdiet proin. Aliquam nulla facilisi cras fermentum. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Ullamcorper eget nulla facilisi etiam dignissim diam quis. Dui nunc mattis enim ut tellus elementum. Convallis convallis tellus id interdum velit laoreet id. Diam ut venenatis tellus in metus. Nullam ac tortor vitae purus. Laoreet sit amet cursus sit. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Accumsan lacus vel facilisis volutpat est velit. Egestas sed sed risus pretium quam vulputate dignissim. Justo eget magna fermentum iaculis eu non diam.
                      <br />
                      A pellentesque sit amet porttitor eget dolor morbi non. Tristique nulla aliquet enim tortor. Augue interdum velit euismod in pellentesque. In nisl nisi scelerisque eu. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Ac feugiat sed lectus vestibulum mattis. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Nunc sed id semper risus in. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Nulla aliquet enim tortor at auctor urna. A scelerisque purus semper eget duis at tellus at. In eu mi bibendum neque egestas congue. In arcu cursus euismod quis. Sit amet luctus venenatis lectus magna fringilla. Pharetra magna ac placerat vestibulum lectus mauris.
                      <br />
                      Cum sociis natoque penatibus et. Ultrices mi tempus imperdiet nulla malesuada. Aenean et tortor at risus viverra. Amet dictum sit amet justo. Ut morbi tincidunt augue interdum velit euismod in. Volutpat consequat mauris nunc congue nisi. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Mauris pellentesque pulvinar pellentesque habitant. Lorem donec massa sapien faucibus et molestie ac feugiat. Morbi tristique senectus et netus. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Vehicula ipsum a arcu cursus vitae. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Magna sit amet purus gravida quis blandit turpis cursus. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque.
                      <br />
                      Pellentesque sit amet porttitor eget dolor. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Lectus quam id leo in vitae. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Enim diam vulputate ut pharetra sit. Tellus pellentesque eu tincidunt tortor. Enim eu turpis egestas pretium aenean. Ut consequat semper viverra nam libero. Integer quis auctor elit sed vulputate. Risus viverra adipiscing at in tellus integer. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Rhoncus aenean vel elit scelerisque mauris pellentesque.
                      <br />
                      Enim lobortis scelerisque fermentum dui faucibus in. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Sem fringilla ut morbi tincidunt augue interdum velit. Tortor pretium viverra suspendisse potenti nullam. Congue quisque egestas diam in arcu cursus. Eget mauris pharetra et ultrices neque ornare. Scelerisque eu ultrices vitae auctor. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Hendrerit gravida rutrum quisque non tellus.
                  </p>
              </div>
              <div className="p-4 w-full flex items-center justify-center"></div>
      </div>
    );
  }
  